### ISSUE TITLE
HTML inside an HTML attribute

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/rocket-lazyload-common#22]
Please find the original HTML of the page here: 
http://snippi.com/s/o9erz6s

Problem begins around line 268. 
There are numerous places where HTML is found within other attributes. 

This breaks our LazyLoad, resulting in this display on the front end:
![Virtuelle_Rundgänge_für_Ihre_Immobilie_☞_Jetzt_schon_ab_1€_Tag](https://user-images.githubusercontent.com/1043076/56252523-09956c00-606d-11e9-8727-9d75f7b9ea40.jpg)

Slack convo: https://wp-media.slack.com/archives/C08N8J6VC/p1555456038103700

**Comment by Tabrisrp** [comment]
I think I fixed this unvoluntarily when doing changes for something else, as I added part of this HTML to the unit tests and the images inside the attribute are not touched anymore.

Feel free to re-open if you encounter it again.
