### ISSUE TITLE
auto-exclude slick-slide-image

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/rocket-lazyload-common#33]
This class is related to a specific image carousel from Elementor
adding `class="slick-slide-image` directly to excluded attributes in Image.php resolves it. 

This is the related code: https://code.elementor.com/classes/elementor-widget_image_carousel/
Not sure if we can do anything to actually be compatible? i.e. LazyLoad the image without issue?

Plot twist: It's only an issue when an image size with 0 height like this is selected: 

![Elementor___Elementor_test](https://user-images.githubusercontent.com/1043076/56924971-19587b80-6a83-11e9-8d68-cc0d9dc089b7.jpg)

Otherwise it works. So I suppose we should only auto-exclude if we can detect when that option is enabled?

Example: http://mega.wp-rocket.me/elementor-test/
(scroll down to heading - Image Carousel)

**Comment by webtrainingwheels** [comment]
Slack convo: https://wp-media.slack.com/archives/G8L4EE8N9/p1557168599002800

**Comment by webtrainingwheels** [comment]
Some extra little info from a customer who had this issue but not using those image options above. In his case: 
>the carousel is centered in an ELEMENTOR SECTION, that stretches the minimum hight to "screen size" or "VH 100%".
https://secure.helpscout.net/conversation/834721297/105281?folderId=377611

**Comment by arunbasillal** [comment]
Hey @webtrainingwheels 

I have been trying to understand this issue. I see white space in the slider as you can see here - https://jmp.sh/yGNxG8D . (It corrects itself after a while.)

Is this the issue? 

Other notes: 

- The slider itself is working correctly. 
- The slider image is LazyLoaded - https://jmp.sh/WX0fMUp
- Exactly the same result if I use another image size - https://jmp.sh/3wXC5aM

What did I miss?

**Comment by webtrainingwheels** [comment]
The issue is the white space under the image.

**Comment by Tabrisrp** [comment]
Testing a bit, looks like it's an issue because of the placeholder. If I remove the width and height values of the placeholder, the display is correct.

**Comment by camilamadronero** [comment]
Related ticket > https://secure.helpscout.net/conversation/857652409/108583?folderId=2675957.
