### ISSUE TITLE
Additional attributes are causing wrong output

### ISSUE THREAD

**Issue by piotrbak** [wp-media/rocket-lazyload-common#35]
Here's the code used by one of our customers:
http://snippi.com/s/97zxc7d

When the following attributes are present (lightbox adds them), our lazy load is replacing SRC value with the SRCSET one destroying the output:
http://snippi.com/s/0z5j2rc

Related HS:
https://secure.helpscout.net/conversation/829806773/104644?folderId=2415573

**Comment by webtrainingwheels** [comment]
Looks like another case here, using the same attributes:
https://secure.helpscout.net/conversation/848144598/107129?folderId=377611

Customer is using the Woocommerce Product Bundles extension.
It seems to work ok in Chrome, but in FF the placeholder is not correctly replaced so the images break. 
Slack convo: https://wp-media.slack.com/archives/C43T1AYMQ/p1557783545006000
