### ISSUE TITLE
Issue with Enfold image module + link

### ISSUE THREAD

**Issue by webtrainingwheels** [wp-media/rocket-lazyload-common#41]
When using Enfold theme, there is an image module in their builder. When using the image alone, LazyLoad works fine. But when a link is added to the image, it breaks - the placeholder is no longer replaced.

We can reproduce the issue here: http://mega.wp-rocket.me/enfold/
Using this image as a test: https://jmp.sh/leKRcXh

Ticket: 
https://secure.helpscout.net/conversation/853870769/108033?folderId=273764

@piotrbak has made some investigations and reported the issue to our LL library here: 
https://github.com/verlok/lazyload/issues/341

**Comment by webtrainingwheels** [comment]
another ticket: https://secure.helpscout.net/conversation/861503760/109156/

tags: `enfold` + `lazyload`

**Comment by camilamadronero** [comment]
Related and self reminder -> notify https://secure.helpscout.net/conversation/860815913/109075/

**Comment by webtrainingwheels** [comment]
Looks like it's fixed with https://github.com/wp-media/rocket-lazyload-common/pull/40 in 3.3.4 beta
