### ISSUE TITLE
WP Rocket v3.3.5.2 Lazyload is not working with rocket-lazyload-common since 2.4

### ISSUE THREAD

**Issue by Gandhi11** [wp-media/rocket-lazyload-common#46]
The changes made in  #45 is breaking the LazyLoad functionality of the WP Rocket v3.3.5.2 plugin since there is no more `window.lazyLoadOptions` because the WP Rocket plugin never call the new `getInlineLazyloadScript` method.

When the `autoInitialize` function is called in the `lazyload.js` of the WP Rocket plugin code, the options variable is undefined.

The WP Rocket plugin has the `"wp-media/rocket-lazyload-common": "^2.2"` dependency so when you do a `composer update` this dependency get updated to the latest version.

For now I forced the `wp-media/rocket-lazyload-common` dependency to `2.3.10` in my projects.

**Comment by Tabrisrp** [comment]
Thank you for your initial report on this issue.

This has been fixed since 3.3.6 of WP Rocket.
