### ISSUE TITLE
Lazy load of Picture elements leads to milliseconds of broken image

### ISSUE THREAD

**Issue by piotrbak** [wp-media/rocket-lazyload-common#47]
When the markup is using `<picture>` element, lazyload causes a millisecond of broken image:
http://recordit.co/ePyCyk7kdi

That's because we are **replacing** `src` attribute with `data-lazy-src` instead of preserving `src` with placeholder as we do for regular `<img>` elements:
https://github.com/wp-media/rocket-lazyload-common/blob/fcebb3db1687ce4f88854c6fbc67a36e8ae9e2bf/src/Image.php#L150

I've performed a simple test and can confirm that preserving `src` attribute with placeholder resolves the problem. I don't know if there are any technical difficulties related to this solution.

Slack convo:
https://wp-media.slack.com/archives/C43T1AYMQ/p1565382103002200

Related ticket:
https://secure.helpscout.net/conversation/924719347/118853/

**Comment by dws122** [comment]
Hi! Checking in to see if there's been any update to this? Is there anything we can do to help correct this issue?

**Comment by JiveDig** [comment]
I'm trying to follow the updates/changelogs but not sure where things are at. Can you confirm whether this made it into one of the current public releases here yet? https://wp-rocket.me/changelog/

We're waiting to push an update to our theme until this patch is released for Rocket.

Thanks ;)

**Comment by Tabrisrp** [comment]
This should be included in WP Rocket starting from version 3.4
